package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type HandlerInfo struct {
	Package    string
	ImportPath string
	Alias      string
	TypeName   string
	Methods    []string
	FilePath   string
}

type RemoteInfo struct {
	Package    string
	ImportPath string
	Alias      string
	TypeName   string
	Methods    []string
	FilePath   string
}

type FilterInfo struct {
	Package    string
	ImportPath string
	Alias      string
	TypeName   string
	Before     bool
	After      bool
	FilePath   string
}

type CronInfo struct {
	Package    string
	ImportPath string
	Alias      string
	TypeName   string
	Methods    []string
	FilePath   string
}

type ServerType struct {
	Name     string
	Handlers []HandlerInfo
	Remotes  []RemoteInfo
	Filters  []FilterInfo
	Crons    []CronInfo
}

type GenData struct {
	Types     []ServerType
	Imports   []ImportInfo
	ImportMap map[string]string
}

type ImportInfo struct {
	Alias string
	Path  string
}

var genTmpl = `// Code generated by gomelo. DO NOT EDIT.

package main

import (
	"gomelo/loader"
{{range .Imports}}
	{{.Alias}} "{{.Path}}"
{{end}}
)

{{range .Types}}
{{$stName := .Name}}
// Register {{.Name}} handlers, remotes, filters and crons
func init() {
	l := loader.GlobalLoader()
	if l == nil {
		return
	}
	{{range .Handlers}}
	h{{.TypeName}} := &{{.Alias}}.{{.TypeName}}{}
	v{{.TypeName}} := loader.ReflectValueOf(h{{.TypeName}})
	t{{.TypeName}} := v{{.TypeName}}.Type()
	for i := 0; i < t{{.TypeName}}.NumMethod(); i++ {
		m := t{{.TypeName}}.Method(i)
		if loader.IsHandlerMethod(m) {
			route := loader.BuildRoute("{{$stName}}", t{{.TypeName}}.Elem().Name(), m.Name)
			l.RegisterHandlerMethod("{{$stName}}", route, h{{.TypeName}}, m)
		}
	}
	{{end}}
	{{range .Remotes}}
	r{{.TypeName}} := &{{.Alias}}.{{.TypeName}}{}
	v{{.TypeName}} := loader.ReflectValueOf(r{{.TypeName}})
	t{{.TypeName}} := v{{.TypeName}}.Type()
	for i := 0; i < t{{.TypeName}}.NumMethod(); i++ {
		m := t{{.TypeName}}.Method(i)
		if loader.IsRemoteMethod(m) {
			l.RegisterRemoteMethod("{{$stName}}", t{{.TypeName}}.Elem().Name(), m.Name, r{{.TypeName}}, m)
		}
	}
	{{end}}
	{{range .Filters}}
	f{{.TypeName}} := &{{.Alias}}.{{.TypeName}}{}
	l.RegisterFilter("{{$stName}}", "{{.TypeName}}", f{{.TypeName}}.Before, f{{.TypeName}}.After)
	{{end}}
	{{range .Crons}}
	c{{.TypeName}} := &{{.Alias}}.{{.TypeName}}{}
	v{{.TypeName}} := loader.ReflectValueOf(c{{.TypeName}})
	t{{.TypeName}} := v{{.TypeName}}.Type()
	for i := 0; i < t{{.TypeName}}.NumMethod(); i++ {
		m := t{{.TypeName}}.Method(i)
		if loader.IsCronMethod(m) {
			l.RegisterCronMethod("{{$stName}}", "{{.TypeName}}", m.Name, c{{.TypeName}}, m)
		}
	}
	{{end}}
}
{{end}}
`

func main() {
	flag.Parse()
	basePath := flag.Arg(0)

	if basePath == "" {
		basePath = "game-server/app/servers"
	}

	absPath, err := filepath.Abs(basePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: invalid path: %v\n", err)
		os.Exit(1)
	}

	if _, err := os.Stat(absPath); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "Error: path does not exist: %s\n", absPath)
		os.Exit(1)
	}

	serverTypes, err := scanServerTypes(absPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning: %v\n", err)
		os.Exit(1)
	}

	if len(serverTypes) == 0 {
		fmt.Println("No server types found.")
		return
	}

	output := filepath.Join(filepath.Dir(absPath), "servers_gen.go")
	if err := generate(output, serverTypes, absPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated: %s\n", output)
}

func scanServerTypes(basePath string) ([]ServerType, error) {
	entries, err := os.ReadDir(basePath)
	if err != nil {
		return nil, err
	}

	var types []ServerType
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		serverType := entry.Name()
		st := ServerType{Name: serverType}

		handlerPath := filepath.Join(basePath, serverType, "handler")
		if info, err := os.Stat(handlerPath); err == nil && info.IsDir() {
			handlers, err := scanHandlers(handlerPath, basePath, serverType)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: error scanning handlers for %s: %v\n", serverType, err)
			} else {
				st.Handlers = handlers
			}
		}

		remotePath := filepath.Join(basePath, serverType, "remote")
		if info, err := os.Stat(remotePath); err == nil && info.IsDir() {
			remotes, err := scanRemotes(remotePath, basePath, serverType)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: error scanning remotes for %s: %v\n", serverType, err)
			} else {
				st.Remotes = remotes
			}
		}

		filterPath := filepath.Join(basePath, serverType, "filter")
		if info, err := os.Stat(filterPath); err == nil && info.IsDir() {
			filters, err := scanFilters(filterPath, basePath, serverType)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: error scanning filters for %s: %v\n", serverType, err)
			} else {
				st.Filters = filters
			}
		}

		cronPath := filepath.Join(basePath, serverType, "cron")
		if info, err := os.Stat(cronPath); err == nil && info.IsDir() {
			crones, err := scanCrons(cronPath, basePath, serverType)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: error scanning crons for %s: %v\n", serverType, err)
			} else {
				st.Crons = crones
			}
		}

		if len(st.Handlers) > 0 || len(st.Remotes) > 0 || len(st.Filters) > 0 || len(st.Crons) > 0 {
			types = append(types, st)
		}
	}

	return types, nil
}

func scanHandlers(dir string, basePath string, serverType string) ([]HandlerInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var allHandlers []HandlerInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		info, err := parseHandlerFile(filePath, basePath, serverType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: error parsing %s: %v\n", filePath, err)
			continue
		}
		if info != nil && len(info.Methods) > 0 {
			allHandlers = append(allHandlers, *info)
		}
	}

	return allHandlers, nil
}

func parseHandlerFile(filePath string, basePath string, serverType string) (*HandlerInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	pkgName := node.Name.Name
	if pkgName == "" {
		pkgName = filepath.Base(filepath.Dir(filePath))
	}

	relPath, _ := filepath.Rel(filepath.Dir(basePath), filepath.Dir(filePath))
	relPath = "./" + relPath

	var handlers []HandlerInfo
	var currentType string
	var methods []string

	for _, decl := range node.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil {
			continue
		}

		typeName := ""
		switch t := funcDecl.Recv.List[0].Type.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}

		if typeName == "" {
			continue
		}

		if !strings.HasSuffix(typeName, "Handler") && !strings.HasSuffix(typeName, "handler") {
			continue
		}

		if funcDecl.Type.Params == nil || len(funcDecl.Type.Params.List) != 1 {
			continue
		}

		if !isContextParam(funcDecl.Type.Params.List[0]) {
			continue
		}

		if currentType != "" && currentType != typeName {
			if len(methods) > 0 {
				handlers = append(handlers, HandlerInfo{
					Package:    pkgName,
					ImportPath: relPath,
					Alias:      pkgName + "_" + serverType,
					TypeName:   currentType,
					Methods:    methods,
					FilePath:   filePath,
				})
			}
			methods = nil
		}
		methods = append(methods, funcDecl.Name.Name)
		currentType = typeName
	}

	if currentType != "" && len(methods) > 0 {
		handlers = append(handlers, HandlerInfo{
			Package:    pkgName,
			ImportPath: relPath,
			Alias:      pkgName + "_" + serverType,
			TypeName:   currentType,
			Methods:    methods,
			FilePath:   filePath,
		})
	}

	if len(handlers) == 0 {
		return nil, nil
	}

	return &handlers[0], nil
}

func scanRemotes(dir string, basePath string, serverType string) ([]RemoteInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var remotes []RemoteInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		info, err := parseRemoteFile(filePath, basePath, serverType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: error parsing %s: %v\n", filePath, err)
			continue
		}
		if info != nil && len(info.Methods) > 0 {
			remotes = append(remotes, *info)
		}
	}

	return remotes, nil
}

func parseRemoteFile(filePath string, basePath string, serverType string) (*RemoteInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	pkgName := node.Name.Name
	if pkgName == "" {
		pkgName = filepath.Base(filepath.Dir(filePath))
	}

	relPath, _ := filepath.Rel(filepath.Dir(basePath), filepath.Dir(filePath))
	relPath = "./" + relPath

	var remotes []RemoteInfo
	var currentType string
	var methods []string

	for _, decl := range node.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil {
			continue
		}

		typeName := ""
		switch t := funcDecl.Recv.List[0].Type.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}

		if typeName == "" {
			continue
		}

		if !strings.HasSuffix(typeName, "Remote") && !strings.HasSuffix(typeName, "remote") {
			continue
		}

		if funcDecl.Type.Params == nil || len(funcDecl.Type.Params.List) != 2 {
			continue
		}

		if !isContextParam(funcDecl.Type.Params.List[0]) {
			continue
		}

		if currentType != "" && currentType != typeName {
			if len(methods) > 0 {
				remotes = append(remotes, RemoteInfo{
					Package:    pkgName,
					ImportPath: relPath,
					Alias:      pkgName + "_" + serverType,
					TypeName:   currentType,
					Methods:    methods,
					FilePath:   filePath,
				})
			}
			methods = nil
		}
		methods = append(methods, funcDecl.Name.Name)
		currentType = typeName
	}

	if currentType != "" && len(methods) > 0 {
		remotes = append(remotes, RemoteInfo{
			Package:    pkgName,
			ImportPath: relPath,
			Alias:      pkgName + "_" + serverType,
			TypeName:   currentType,
			Methods:    methods,
			FilePath:   filePath,
		})
	}

	if len(remotes) == 0 {
		return nil, nil
	}

	return &remotes[0], nil
}

func scanFilters(dir string, basePath string, serverType string) ([]FilterInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var allFilters []FilterInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		info, err := parseFilterFile(filePath, basePath, serverType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: error parsing %s: %v\n", filePath, err)
			continue
		}
		if info != nil {
			allFilters = append(allFilters, *info)
		}
	}

	return allFilters, nil
}

func parseFilterFile(filePath string, basePath string, serverType string) (*FilterInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	pkgName := node.Name.Name
	if pkgName == "" {
		pkgName = filepath.Base(filepath.Dir(filePath))
	}

	relPath, _ := filepath.Rel(filepath.Dir(basePath), filepath.Dir(filePath))
	relPath = "./" + relPath

	var filters []FilterInfo
	var currentType string
	var hasBefore, hasAfter bool

	for _, decl := range node.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil {
			continue
		}

		typeName := ""
		switch t := funcDecl.Recv.List[0].Type.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}

		if typeName == "" {
			continue
		}

		if !strings.HasSuffix(typeName, "Filter") && !strings.HasSuffix(typeName, "filter") {
			continue
		}

		if currentType != "" && currentType != typeName {
			filters = append(filters, FilterInfo{
				Package:    pkgName,
				ImportPath: relPath,
				Alias:      pkgName + "_" + serverType,
				TypeName:   currentType,
				Before:     hasBefore,
				After:      hasAfter,
				FilePath:   filePath,
			})
			hasBefore = false
			hasAfter = false
		}

		if funcDecl.Name.Name == "Before" {
			hasBefore = true
		} else if funcDecl.Name.Name == "After" {
			hasAfter = true
		}
		currentType = typeName
	}

	if currentType != "" {
		filters = append(filters, FilterInfo{
			Package:    pkgName,
			ImportPath: relPath,
			Alias:      pkgName + "_" + serverType,
			TypeName:   currentType,
			Before:     hasBefore,
			After:      hasAfter,
			FilePath:   filePath,
		})
	}

	if len(filters) == 0 {
		return nil, nil
	}

	return &filters[0], nil
}

func scanCrons(dir string, basePath string, serverType string) ([]CronInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var allCrons []CronInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		info, err := parseCronFile(filePath, basePath, serverType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: error parsing %s: %v\n", filePath, err)
			continue
		}
		if info != nil && len(info.Methods) > 0 {
			allCrons = append(allCrons, *info)
		}
	}

	return allCrons, nil
}

func parseCronFile(filePath string, basePath string, serverType string) (*CronInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	pkgName := node.Name.Name
	if pkgName == "" {
		pkgName = filepath.Base(filepath.Dir(filePath))
	}

	relPath, _ := filepath.Rel(filepath.Dir(basePath), filepath.Dir(filePath))
	relPath = "./" + relPath

	var crons []CronInfo
	var currentType string
	var methods []string

	for _, decl := range node.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil {
			continue
		}

		typeName := ""
		switch t := funcDecl.Recv.List[0].Type.(type) {
		case *ast.Ident:
			typeName = t.Name
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				typeName = ident.Name
			}
		}

		if typeName == "" {
			continue
		}

		if !strings.HasSuffix(typeName, "Cron") && !strings.HasSuffix(typeName, "cron") {
			continue
		}

		if funcDecl.Type.Params != nil && len(funcDecl.Type.Params.List) > 0 {
			continue
		}

		if currentType != "" && currentType != typeName {
			crons = append(crons, CronInfo{
				Package:    pkgName,
				ImportPath: relPath,
				Alias:      pkgName + "_" + serverType,
				TypeName:   currentType,
				Methods:    methods,
				FilePath:   filePath,
			})
			methods = nil
		}
		methods = append(methods, funcDecl.Name.Name)
		currentType = typeName
	}

	if currentType != "" && len(methods) > 0 {
		crons = append(crons, CronInfo{
			Package:    pkgName,
			ImportPath: relPath,
			Alias:      pkgName + "_" + serverType,
			TypeName:   currentType,
			Methods:    methods,
			FilePath:   filePath,
		})
	}

	if len(crons) == 0 {
		return nil, nil
	}

	return &crons[0], nil
}

func isContextParam(field *ast.Field) bool {
	if field.Type == nil {
		return false
	}

	switch t := field.Type.(type) {
	case *ast.Ident:
		return t.Name == "Context"
	case *ast.StarExpr:
		if sel, ok := t.X.(*ast.SelectorExpr); ok {
			if sel.Sel != nil && sel.Sel.Name == "Context" {
				return true
			}
		}
	case *ast.SelectorExpr:
		if t.Sel != nil && t.Sel.Name == "Context" {
			return true
		}
	}
	return false
}

func generate(output string, types []ServerType, basePath string) error {
	t, err := template.New("servers_gen").Parse(genTmpl)
	if err != nil {
		return err
	}

	imports := buildImports(types, basePath)
	importMap := make(map[string]string)
	for _, imp := range imports {
		importMap[imp.Path] = imp.Alias
	}

	data := GenData{
		Types:     types,
		Imports:   imports,
		ImportMap: importMap,
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}

	return os.WriteFile(output, buf.Bytes(), 0644)
}

func buildImports(types []ServerType, basePath string) []ImportInfo {
	seen := make(map[string]bool)
	var imports []ImportInfo

	moduleName := getModuleName()

	for _, st := range types {
		for _, h := range st.Handlers {
			if h.ImportPath == "" {
				continue
			}
			fullPath := resolveImportPath(h.ImportPath, basePath, moduleName)
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := h.Package + "_" + st.Name
			imports = append(imports, ImportInfo{
				Alias: alias,
				Path:  fullPath,
			})
		}
		for _, r := range st.Remotes {
			if r.ImportPath == "" {
				continue
			}
			fullPath := resolveImportPath(r.ImportPath, basePath, moduleName)
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := r.Package + "_" + st.Name
			imports = append(imports, ImportInfo{
				Alias: alias,
				Path:  fullPath,
			})
		}
		for _, f := range st.Filters {
			if f.ImportPath == "" {
				continue
			}
			fullPath := resolveImportPath(f.ImportPath, basePath, moduleName)
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := f.Package + "_" + st.Name
			imports = append(imports, ImportInfo{
				Alias: alias,
				Path:  fullPath,
			})
		}
		for _, c := range st.Crons {
			if c.ImportPath == "" {
				continue
			}
			fullPath := resolveImportPath(c.ImportPath, basePath, moduleName)
			if seen[fullPath] {
				continue
			}
			seen[fullPath] = true
			alias := c.Package + "_" + st.Name
			imports = append(imports, ImportInfo{
				Alias: alias,
				Path:  fullPath,
			})
		}
	}

	return imports
}

func getModuleName() string {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return ""
	}
	lines := strings.Split(string(data), "\n")
	if len(lines) > 0 && strings.HasPrefix(lines[0], "module ") {
		return strings.TrimPrefix(lines[0], "module ")
	}
	return ""
}

func resolveImportPath(relPath string, basePath string, moduleName string) string {
	relPath = strings.TrimPrefix(relPath, "./")
	relPath = strings.TrimPrefix(relPath, ".")
	if moduleName == "" {
		return relPath
	}
	absBase, err := filepath.Abs(basePath)
	if err != nil {
		return relPath
	}
	cwd, err := os.Getwd()
	if err != nil {
		return relPath
	}
	rel, err := filepath.Rel(cwd, absBase)
	if err != nil {
		return relPath
	}
	rel = strings.TrimPrefix(rel, ".")
	rel = strings.TrimPrefix(rel, string(filepath.Separator))
	rel = filepath.ToSlash(rel)
	relPath = filepath.ToSlash(relPath)

	baseName := filepath.Base(basePath)
	relPath = strings.TrimPrefix(relPath, baseName+"/")

	return moduleName + "/" + rel + "/" + relPath
}
